version: 2

machine:
  timezone: Europe/Paris

jobs:
  build:
    working_directory: /go/src/cachet/cli
    docker:
      - image: circleci/golang:1.8
        environment:
          GOPATH: /go
    steps:
      - checkout:
          path: /go/src/cachet
      - run:
          name: Checking GO version...
          command: go version
      - run:
          name: Checking directory...
          command: ls -l
      - run:
          name: Downloading dependencies...
          command: go get .
      - run:
          name: Building...
          command: go build -o cachet_monitor

  test:
    working_directory: /go/src/cachet
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Listing build version...
          command: cd cli ; ./cachet_monitor --version

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:	
            - build