version: 2
jobs:
  build:
    working_directory: /go/src/github.com/veekeefr/cachet-monitor
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run:
          name: Building...
          command: go version

workflows:
  version: 2
  build_and_test:
    jobs:
      - build